# Real U50 Fast Uniform Benchmark: GAP + MILP + Genetic

Быстрый ноутбук для уменьшенного датасета, где задачи урезаются пространственно-равномерно,
а агенты урезаются равномерно по депо с запасом по сменному времени.

Основной параметр: `DOWNSCALE_FACTOR` (например, `2..10`).

In [1]:
from __future__ import annotations

from pathlib import Path
import sys
import json
import importlib
import inspect
import pandas as pd


def find_repo_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "src").exists() and (candidate / "notebooks").exists():
            return candidate
    raise RuntimeError("Repo root not found")


REPO_ROOT = find_repo_root(Path.cwd().resolve())
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

# Clean cached modules to avoid stale code in long-lived kernels.
for mod_name in list(sys.modules):
    if mod_name.startswith("flowopt"):
        sys.modules.pop(mod_name, None)

import flowopt.pipeline as fp
from flowopt.pipelines.u50_fast_dataset import build_fast_u50_dataset

fp = importlib.reload(fp)

run_real_gap_vrp = fp.run_real_gap_vrp
run_real_milp = fp.run_real_milp
run_real_genetic = fp.run_real_genetic

milp_sig = inspect.signature(run_real_milp)
if "time_limit_sec" not in milp_sig.parameters:
    raise RuntimeError(f"Stale run_real_milp loaded: signature={milp_sig}")

pd.set_option("display.max_colwidth", 160)
print("REPO_ROOT:", REPO_ROOT)
print("pipeline module:", fp.__file__)
print("run_real_milp signature:", milp_sig)

REPO_ROOT: C:\Users\Пользователь\Optimization-of-flows-3
pipeline module: C:\Users\Пользователь\Optimization-of-flows-3\src\flowopt\pipeline.py
run_real_milp signature: (*, dataset_path: 'Path | str' = WindowsPath('C:/Users/Пользователь/Optimization-of-flows-3/src/data/real/real_simple/dataset_real_spb_simple.json'), time_limit_sec: 'int' = 60, unassigned_penalty: 'float' = 100000.0, show_progress: 'bool' = False, progress_hook: 'Callable[[str], None] | None' = None) -> 'RunMetrics'

In [7]:
# Build reduced dataset variant (uniform by depot/space)
BASE_DATASET_PATH = REPO_ROOT / "src" / "data" / "real" / "day_load_profiles" / "u50" / "simplified_a_only" / "dataset_real_spb_day_u50_A_only_simplified.json"
FAST_ROOT = REPO_ROOT / "src" / "data" / "real" / "day_load_profiles" / "u50" / "fast_uniform"
FAST_ROOT.mkdir(parents=True, exist_ok=True)

DOWNSCALE_FACTOR = 10  # try 2..10
SEED = 42
GRID_SIZE = 6
SAFETY_UTILIZATION = 0.85
FORCE_REBUILD = False

factor_tag = f"f{int(DOWNSCALE_FACTOR) if float(DOWNSCALE_FACTOR).is_integer() else str(DOWNSCALE_FACTOR).replace('.', '_')}"
DATASET_PATH = FAST_ROOT / f"dataset_real_spb_day_u50_fast_{factor_tag}.json"
SUMMARY_PATH = FAST_ROOT / f"summary_real_spb_day_u50_fast_{factor_tag}.json"

if FORCE_REBUILD or not DATASET_PATH.exists() or not SUMMARY_PATH.exists():
    summary = build_fast_u50_dataset(
        base_dataset_path=BASE_DATASET_PATH,
        out_dataset_path=DATASET_PATH,
        downscale_factor=float(DOWNSCALE_FACTOR),
        seed=SEED,
        grid_size=GRID_SIZE,
        safety_utilization=SAFETY_UTILIZATION,
    )
else:
    summary = json.loads(SUMMARY_PATH.read_text(encoding="utf-8"))

print("BASE_DATASET_PATH:", BASE_DATASET_PATH)
print("DATASET_PATH     :", DATASET_PATH)
print("SUMMARY_PATH     :", SUMMARY_PATH)
print("before ->", summary["before"])
print("after  ->", summary["after"])

pd.DataFrame(
    {
        "depot_id": list(summary["selected_tasks_by_depot"].keys()),
        "tasks_selected": list(summary["selected_tasks_by_depot"].values()),
        "agents_selected": [summary["selected_agents_by_depot"][d] for d in summary["selected_tasks_by_depot"].keys()],
        "required_agents_time_model": [summary["required_agents_by_depot"][d] for d in summary["selected_tasks_by_depot"].keys()],
        "required_hours_time_model": [summary["required_hours_by_depot"][d] for d in summary["selected_tasks_by_depot"].keys()],
    }
).sort_values("tasks_selected", ascending=False)

BASE_DATASET_PATH: C:\Users\Пользователь\Optimization-of-flows-3\src\data\real\day_load_profiles\u50\simplified_a_only\dataset_real_spb_day_u50_A_only_simplified.json
DATASET_PATH     : C:\Users\Пользователь\Optimization-of-flows-3\src\data\real\day_load_profiles\u50\fast_uniform\dataset_real_spb_day_u50_fast_f10.json
SUMMARY_PATH     : C:\Users\Пользователь\Optimization-of-flows-3\src\data\real\day_load_profiles\u50\fast_uniform\summary_real_spb_day_u50_fast_f10.json
before -> {'agents': 432, 'tasks': 301, 'mno_nodes': 265}
after  -> {'agents': 50, 'tasks': 32, 'mno_nodes': 32, 'task_sources': 32}

,depot_id,tasks_selected,agents_selected,required_agents_time_model,required_hours_time_model
0,1533456031,15,9,9,105.742239
3,230361,10,17,5,51.709893
2,1903257537,6,6,3,33.583799
1,1746883131,1,18,1,6.696456

In [8]:
# Dataset inspection + optional profile patching
import flowopt.core as core
import flowopt.genetic_solver_components as ga

with DATASET_PATH.open("r", encoding="utf-8") as f:
    dataset = json.load(f)

meta = dataset.get("metadata", {})
counts = {
    "nodes": len(dataset.get("graph", {}).get("nodes", [])),
    "edges": len(dataset.get("graph", {}).get("edges", [])),
    "agents": len(dataset.get("agents", [])),
    "tasks": len(dataset.get("tasks", [])),
    "objects": len({t.get("destination_node_id") for t in dataset.get("tasks", [])}),
    "sources": len({t.get("source_node_id") for t in dataset.get("tasks", [])}),
}

print("dataset name:", meta.get("name"))
print("counts:", counts)
print("fast_profile:", meta.get("fast_profile", {}))

APPLY_PROFILE_LIMITS = True
if APPLY_PROFILE_LIMITS:
    profiles = meta.get("vehicle_profiles", {})
    for vt, p in profiles.items():
        km = float(p.get("max_daily_km", core.MAX_DAILY_KM_BY_TYPE.get(vt, 130.0)))
        hh = float(p.get("max_shift_hours", core.MAX_SHIFT_HOURS_BY_TYPE.get(vt, 10.0)))
        sp = float(p.get("avg_speed_kmph", core.AVG_SPEED_KMPH_BY_TYPE.get(vt, 24.0)))
        core.MAX_DAILY_KM_BY_TYPE[vt] = km
        core.MAX_SHIFT_HOURS_BY_TYPE[vt] = hh
        core.AVG_SPEED_KMPH_BY_TYPE[vt] = sp
        ga.MAX_DAILY_KM_BY_TYPE[vt] = km
        ga.MAX_SHIFT_HOURS_BY_TYPE[vt] = hh
        ga.AVG_SPEED_KMPH_BY_TYPE[vt] = sp

    print("Patched limits from vehicle_profiles for:", sorted(profiles.keys()))

pd.DataFrame([counts])

dataset name: real_spb_u50_fast_f10
counts: {'nodes': 46730, 'edges': 127100, 'agents': 50, 'tasks': 32, 'objects': 5, 'sources': 32}
fast_profile: {'source_dataset': 'C:\\Users\\Пользователь\\Optimization-of-flows-3\\src\\data\\real\\day_load_profiles\\u50\\simplified_a_only\\dataset_real_spb_day_u50_A_only_simplified.json', 'downscale_factor': 10.0, 'seed': 42, 'grid_size': 6, 'safety_utilization': 0.85, 'selected_tasks': 32, 'selected_agents': 50, 'demoted_mno_to_road': 233, 'required_agents_by_depot': {'1533456031': 9, '1746883131': 1, '1903257537': 3, '230361': 5}, 'selected_agents_by_depot': {'1533456031': 9, '1746883131': 18, '1903257537': 6, '230361': 17}, 'selected_tasks_by_depot': {'1533456031': 15, '1746883131': 1, '1903257537': 6, '230361': 10}, 'required_hours_by_depot': {'1533456031': 105.742239, '1746883131': 6.696456, '1903257537': 33.583799, '230361': 51.709893}}
Patched limits from vehicle_profiles for: ['VT_A', 'VT_AB', 'VT_ABD', 'VT_AD', 'VT_C', 'VT_CD']

   nodes   edges  agents  tasks  objects  sources
0  46730  127100      50     32        5       32

In [9]:
# Fast run of 3 algorithms
from time import perf_counter
from datetime import datetime

# GAP
GAP_STEP1_METHOD = "lp"
GAP_ITER = 20
MAX_AGENTS = None

# MILP
RMILP_TIME_LIMIT_SEC = 90
RMILP_UNASSIGNED_PENALTY = 1e7

# Genetic (kept moderate for speed)
GA_POPULATION_SIZE = 20
GA_GENERATIONS = 20
GA_ELITE_SIZE = 3
GA_SEED = 42
GA_GENERATION_SCALE = 1.0
GA_MIN_GENERATIONS = 10

SHOW_ALGO_PROGRESS = True
SHOW_SOLVER_DETAILS = False
REQUIRE_FULL_ASSIGNMENT = False


def make_progress_logger(enabled: bool):
    if not enabled:
        return None
    t0 = perf_counter()
    def _log(message: str) -> None:
        dt = perf_counter() - t0
        print(f"[+{dt:7.1f}s] {message}", flush=True)
    return _log


progress_log = make_progress_logger(SHOW_ALGO_PROGRESS)


def run_with_live_status(label, fn, **kwargs):
    if progress_log is not None:
        progress_log(f"{label}: START")
    ts = perf_counter()
    out = fn(**kwargs)
    if progress_log is not None:
        progress_log(f"{label}: DONE in {perf_counter() - ts:.1f}s")
    return out


results = [
    run_with_live_status(
        "GAP-VRP",
        run_real_gap_vrp,
        dataset_path=DATASET_PATH,
        step1_method=GAP_STEP1_METHOD,
        gap_iter=GAP_ITER,
        max_agents=MAX_AGENTS,
        use_repair=True,
        show_progress=SHOW_SOLVER_DETAILS,
        verbose=False,
        progress_hook=progress_log,
    ),
    run_with_live_status(
        "REAL-MILP",
        run_real_milp,
        dataset_path=DATASET_PATH,
        time_limit_sec=RMILP_TIME_LIMIT_SEC,
        unassigned_penalty=RMILP_UNASSIGNED_PENALTY,
        show_progress=SHOW_SOLVER_DETAILS,
        progress_hook=progress_log,
    ),
    run_with_live_status(
        "REAL-GENETIC",
        run_real_genetic,
        dataset_path=DATASET_PATH,
        population_size=GA_POPULATION_SIZE,
        generations=GA_GENERATIONS,
        elite_size=GA_ELITE_SIZE,
        seed=GA_SEED,
        generation_scale=GA_GENERATION_SCALE,
        min_generations=GA_MIN_GENERATIONS,
        show_progress=SHOW_SOLVER_DETAILS,
        progress_hook=progress_log,
    ),
]

benchmark_df = pd.DataFrame([r.as_dict() for r in results])
benchmark_df = benchmark_df.sort_values(
    by=["all_checks_ok", "transport_work_ton_km", "total_km", "runtime_sec"],
    ascending=[False, True, True, True],
    na_position="last",
).reset_index(drop=True)

# Save benchmark artifact
LOCAL_OUT_DIR = REPO_ROOT / "notebooks" / "local" / "real_data" / "u50_fast_uniform" / factor_tag
LOCAL_OUT_DIR.mkdir(parents=True, exist_ok=True)
RUN_TAG = datetime.now().strftime("%Y%m%d_%H%M%S")
RESULT_JSON_PATH = LOCAL_OUT_DIR / f"benchmark_u50_fast_{factor_tag}_{RUN_TAG}.json"

records = benchmark_df.where(pd.notna(benchmark_df), None).to_dict(orient="records")
artifact = {
    "created_at": datetime.now().isoformat(timespec="seconds"),
    "notebook": "real_u50_fast_uniform_3algo_benchmark.ipynb",
    "dataset_path": str(DATASET_PATH),
    "config": {
        "downscale_factor": DOWNSCALE_FACTOR,
        "seed": SEED,
        "grid_size": GRID_SIZE,
        "safety_utilization": SAFETY_UTILIZATION,
        "gap_step1_method": GAP_STEP1_METHOD,
        "gap_iter": GAP_ITER,
        "max_agents": MAX_AGENTS,
        "rmilp_time_limit_sec": RMILP_TIME_LIMIT_SEC,
        "rmilp_unassigned_penalty": RMILP_UNASSIGNED_PENALTY,
        "ga_population_size": GA_POPULATION_SIZE,
        "ga_generations": GA_GENERATIONS,
        "ga_elite_size": GA_ELITE_SIZE,
        "ga_seed": GA_SEED,
        "ga_generation_scale": GA_GENERATION_SCALE,
        "ga_min_generations": GA_MIN_GENERATIONS,
    },
    "results": records,
}
RESULT_JSON_PATH.write_text(json.dumps(artifact, ensure_ascii=False, indent=2), encoding="utf-8")
print("Saved:", RESULT_JSON_PATH)

if REQUIRE_FULL_ASSIGNMENT:
    if (benchmark_df["unassigned_tasks"].fillna(10**9) > 0).any():
        raise AssertionError("Some algorithms still have unassigned tasks")

main_cols = [
    "algorithm",
    "feasible",
    "all_checks_ok",
    "assigned_routes",
    "unassigned_tasks",
    "active_agents",
    "transport_work_ton_km",
    "total_km",
    "deadhead_km",
    "deadhead_share_pct",
    "total_hours",
    "runtime_sec",
    "solver_error",
]
benchmark_df[[c for c in main_cols if c in benchmark_df.columns]]

[+    0.0s] GAP-VRP: START
[+    0.0s] [real_gap_vrp] load dataset: C:\Users\Пользователь\Optimization-of-flows-3\src\data\real\day_load_profiles\u50\fast_uniform\dataset_real_spb_day_u50_fast_f10.json
[+    1.7s] [real_gap_vrp] dataset loaded (nodes=46730, edges=127100, agents=50, tasks=32)
[+    1.7s] [real_gap_vrp] build nx graph
[+    2.1s] [real_gap_vrp] solver start
[+    2.1s] [real_gap_vrp] [GAP-VRP] start: GAP-Lagrangean + VRP(NN+2opt) [step1=lp]
[+    2.1s] [real_gap_vrp] [GAP-VRP] step1: task generation
[+    2.1s] [real_gap_vrp] [GAP-step1] LP setup: sources=32, sinks=9, variables=288, total_waste_tons=37.617
[+    3.2s] [real_gap_vrp] [GAP-step1] distance matrix: sources=1/32, elapsed=1.2s
[+    4.0s] [real_gap_vrp] [GAP-step1] distance matrix: sources=2/32, elapsed=1.9s
[+    4.7s] [real_gap_vrp] [GAP-step1] distance matrix: sources=3/32, elapsed=2.6s
[+    5.5s] [real_gap_vrp] [GAP-step1] distance matrix: sources=4/32, elapsed=3.4s
[+    6.3s] [real_gap_vrp] [GAP-step1] distance matrix: sources=5/32, elapsed=4.2s
[+    6.9s] [real_gap_vrp] [GAP-step1] distance matrix: sources=6/32, elapsed=4.8s
[+    8.1s] [real_gap_vrp] [GAP-step1] distance matrix: sources=7/32, elapsed=6.0s
[+    8.9s] [real_gap_vrp] [GAP-step1] distance matrix: sources=8/32, elapsed=6.8s
[+    9.7s] [real_gap_vrp] [GAP-step1] distance matrix: sources=9/32, elapsed=7.6s
[+   10.2s] [real_gap_vrp] [GAP-step1] distance matrix: sources=10/32, elapsed=8.2s
[+   10.8s] [real_gap_vrp] [GAP-step1] distance matrix: sources=11/32, elapsed=8.7s
[+   11.8s] [real_gap_vrp] [GAP-step1] distance matrix: sources=12/32, elapsed=9.7s
[+   12.5s] [real_gap_vrp] [GAP-step1] distance matrix: sources=13/32, elapsed=10.4s
[+   13.1s] [real_gap_vrp] [GAP-step1] distance matrix: sources=14/32, elapsed=11.1s
[+   13.7s] [real_gap_vrp] [GAP-step1] distance matrix: sources=15/32, elapsed=11.7s
[+   14.3s] [real_gap_vrp] [GAP-step1] distance matrix: sources=16/32, elapsed=12.2s
[+   14.8s] [real_gap_vrp] [GAP-step1] distance matrix: sources=17/32, elapsed=12.7s
[+   15.9s] [real_gap_vrp] [GAP-step1] distance matrix: sources=18/32, elapsed=13.9s
[+   16.7s] [real_gap_vrp] [GAP-step1] distance matrix: sources=19/32, elapsed=14.6s
[+   17.9s] [real_gap_vrp] [GAP-step1] distance matrix: sources=20/32, elapsed=15.8s
[+   19.0s] [real_gap_vrp] [GAP-step1] distance matrix: sources=21/32, elapsed=16.9s
[+   21.2s] [real_gap_vrp] [GAP-step1] distance matrix: sources=22/32, elapsed=19.1s
[+   22.3s] [real_gap_vrp] [GAP-step1] distance matrix: sources=23/32, elapsed=20.2s
[+   23.8s] [real_gap_vrp] [GAP-step1] distance matrix: sources=24/32, elapsed=21.7s
[+   25.0s] [real_gap_vrp] [GAP-step1] distance matrix: sources=25/32, elapsed=22.9s
[+   26.7s] [real_gap_vrp] [GAP-step1] distance matrix: sources=26/32, elapsed=24.6s
[+   28.9s] [real_gap_vrp] [GAP-step1] distance matrix: sources=27/32, elapsed=26.8s
[+   30.4s] [real_gap_vrp] [GAP-step1] distance matrix: sources=28/32, elapsed=28.3s
[+   32.0s] [real_gap_vrp] [GAP-step1] distance matrix: sources=29/32, elapsed=29.9s
[+   33.7s] [real_gap_vrp] [GAP-step1] distance matrix: sources=30/32, elapsed=31.6s
[+   35.9s] [real_gap_vrp] [GAP-step1] distance matrix: sources=31/32, elapsed=33.8s
[+   39.0s] [real_gap_vrp] [GAP-step1] distance matrix: sources=32/32, elapsed=37.0s
[+   39.0s] [real_gap_vrp] [GAP-step1] distance matrix built in 37.0s
[+   39.1s] [real_gap_vrp] [GAP-step1] LP eq constraints built: 32 rows in 0.0s
[+   39.1s] [real_gap_vrp] [GAP-step1] LP ub constraints built: 9 rows in 0.0s
[+   39.1s] [real_gap_vrp] [GAP-step1] linprog start: method=highs
[+   39.1s] [real_gap_vrp] [GAP-step1] linprog done in 0.1s: success=True, status=0
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=1/32, tasks=1, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=2/32, tasks=2, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=3/32, tasks=3, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=4/32, tasks=4, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=5/32, tasks=5, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=6/32, tasks=6, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=7/32, tasks=7, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=8/32, tasks=8, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=9/32, tasks=9, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=10/32, tasks=10, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=11/32, tasks=11, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=12/32, tasks=12, elapsed=0.0s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=13/32, tasks=13, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=14/32, tasks=14, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=15/32, tasks=15, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=16/32, tasks=16, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=17/32, tasks=17, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=18/32, tasks=18, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=19/32, tasks=19, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=20/32, tasks=20, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=21/32, tasks=21, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=22/32, tasks=22, elapsed=0.1s
[+   39.2s] [real_gap_vrp] [GAP-step1] build tasks: sources=23/32, tasks=23, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] build tasks: sources=24/32, tasks=24, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] build tasks: sources=25/32, tasks=25, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] build tasks: sources=26/32, tasks=26, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] build tasks: sources=27/32, tasks=27, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] build tasks: sources=28/32, tasks=28, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] build tasks: sources=29/32, tasks=29, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] build tasks: sources=30/32, tasks=30, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] build tasks: sources=31/32, tasks=31, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] build tasks: sources=32/32, tasks=32, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-step1] step1 LP tasks built: tasks=32, elapsed=0.1s
[+   39.3s] [real_gap_vrp] [GAP-VRP] step1 done in 37.2s, tasks=32
[+   39.3s] [real_gap_vrp] [GAP-VRP] step2: GAP Lagrangean, iter=20
[+   39.3s] [real_gap_vrp] [GAP-LR] prepare matrices: agents=50, tasks=32, max_iter=20
[+   42.2s] [real_gap_vrp] [GAP-LR] precompute costs: 5/50 agents
[+   48.2s] [real_gap_vrp] [GAP-LR] precompute costs: 10/50 agents
[+   48.2s] [real_gap_vrp] [GAP-LR] precompute costs: 15/50 agents
[+   48.2s] [real_gap_vrp] [GAP-LR] precompute costs: 20/50 agents
[+   48.2s] [real_gap_vrp] [GAP-LR] precompute costs: 25/50 agents
[+   52.1s] [real_gap_vrp] [GAP-LR] precompute costs: 30/50 agents
[+   56.9s] [real_gap_vrp] [GAP-LR] precompute costs: 35/50 agents
[+   56.9s] [real_gap_vrp] [GAP-LR] precompute costs: 40/50 agents
[+   56.9s] [real_gap_vrp] [GAP-LR] precompute costs: 45/50 agents
[+   56.9s] [real_gap_vrp] [GAP-LR] precompute costs: 50/50 agents
[+   56.9s] [real_gap_vrp] [GAP-LR] precompute done
[+   56.9s] [real_gap_vrp] [GAP-LR] iter 1/20 started
[+   58.1s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+   59.2s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+   60.1s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+   60.9s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+   61.7s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+   62.6s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+   63.7s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+   64.7s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+   66.1s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+   67.1s] [real_gap_vrp] [GAP-LR] iter 1/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+   67.1s] [real_gap_vrp] [GAP-LR] iter 1/20 done: LB=1302.80, UB=inf, assigned=0/32, iter_sec=10.1
[+   67.1s] [real_gap_vrp] [GAP-LR] iter 2/20 started
[+   68.2s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+   69.3s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+   70.1s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+   70.9s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+   71.7s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+   72.7s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+   73.9s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+   74.9s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+   76.0s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+   76.8s] [real_gap_vrp] [GAP-LR] iter 2/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+   76.8s] [real_gap_vrp] [GAP-LR] iter 2/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=9.7
[+  631.8s] [real_gap_vrp] [GAP-LR] iter 4/20 started
[+  633.0s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+  633.7s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+  634.2s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+  634.7s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+  635.5s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+  636.6s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+  637.7s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+  638.7s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+  640.1s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+  641.1s] [real_gap_vrp] [GAP-LR] iter 4/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+  641.1s] [real_gap_vrp] [GAP-LR] iter 4/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=9.4
[+  652.3s] [real_gap_vrp] [GAP-LR] iter 6/20 started
[+  653.5s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+  654.7s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+  655.6s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+  656.4s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+  657.2s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+  658.2s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+  659.2s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+  660.2s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+  661.3s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+  662.3s] [real_gap_vrp] [GAP-LR] iter 6/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+  662.3s] [real_gap_vrp] [GAP-LR] iter 6/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=10.0
[+  672.4s] [real_gap_vrp] [GAP-LR] iter 8/20 started
[+  673.6s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+  674.7s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+  675.6s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+  676.4s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+  677.2s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+  678.4s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+  679.6s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+  680.7s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+  681.9s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+  682.9s] [real_gap_vrp] [GAP-LR] iter 8/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+  682.9s] [real_gap_vrp] [GAP-LR] iter 8/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=10.5
[+  695.1s] [real_gap_vrp] [GAP-LR] iter 10/20 started
[+  696.6s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+  697.9s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+  699.0s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+  700.6s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+  701.8s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+  703.3s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+  704.7s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+  706.0s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+  707.4s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+  708.5s] [real_gap_vrp] [GAP-LR] iter 10/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+  708.5s] [real_gap_vrp] [GAP-LR] iter 10/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=13.4
[+  718.8s] [real_gap_vrp] [GAP-LR] iter 12/20 started
[+  719.9s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+  721.0s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+  721.8s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+  722.6s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+  723.4s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+  724.3s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+  725.5s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+  726.5s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+  727.6s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+  728.6s] [real_gap_vrp] [GAP-LR] iter 12/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+  728.6s] [real_gap_vrp] [GAP-LR] iter 12/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=9.8
[+  738.4s] [real_gap_vrp] [GAP-LR] iter 14/20 started
[+  739.5s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+  740.6s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+  741.4s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+  742.0s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+  742.6s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+  743.5s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+  744.6s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+  745.6s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+  746.8s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+  748.0s] [real_gap_vrp] [GAP-LR] iter 14/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+  748.0s] [real_gap_vrp] [GAP-LR] iter 14/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=9.6
[+  757.7s] [real_gap_vrp] [GAP-LR] iter 16/20 started
[+  759.1s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+  760.3s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+  761.2s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+  762.0s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+  762.8s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+  763.9s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+  765.3s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+  766.4s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+  767.5s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+  768.5s] [real_gap_vrp] [GAP-LR] iter 16/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+  768.5s] [real_gap_vrp] [GAP-LR] iter 16/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=10.8
[+  778.4s] [real_gap_vrp] [GAP-LR] iter 18/20 started
[+  779.7s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+ 1402.5s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+ 1403.0s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+ 1403.3s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+ 1403.7s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+ 1404.1s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+ 1404.7s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+ 1405.0s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+ 1405.5s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+ 1405.8s] [real_gap_vrp] [GAP-LR] iter 18/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+ 1405.8s] [real_gap_vrp] [GAP-LR] iter 18/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=627.5
[+ 1416.8s] [real_gap_vrp] [GAP-LR] iter 20/20 started
[+ 1418.5s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 5/50, id=AGENT_00277, free_tasks=32
[+ 1419.6s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 10/50, id=AGENT_00516, free_tasks=31
[+ 1420.5s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 15/50, id=AGENT_00443, free_tasks=32
[+ 1421.3s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 20/50, id=AGENT_00392, free_tasks=31
[+ 1422.2s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 25/50, id=AGENT_00433, free_tasks=32
[+ 1423.3s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 30/50, id=AGENT_00344, free_tasks=32
[+ 1424.6s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 35/50, id=AGENT_00118, free_tasks=32
[+ 1425.7s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 40/50, id=AGENT_00117, free_tasks=32
[+ 1426.8s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 45/50, id=AGENT_00083, free_tasks=32
[+ 1427.8s] [real_gap_vrp] [GAP-LR] iter 20/20, agent 50/50, id=AGENT_00030, free_tasks=32
[+ 1427.8s] [real_gap_vrp] [GAP-LR] iter 20/20 done: LB=-2058.57, UB=inf, assigned=0/32, iter_sec=11.0
[+ 1427.8s] [real_gap_vrp] [GAP-LR] no feasible dual assignment found, run greedy repair
[+ 1427.8s] [real_gap_vrp] [GAP-LR] gap allocation ready
[+ 1427.8s] [real_gap_vrp] [GAP-VRP] step2 done in 1388.5s, assigned_after_gap=32/32
[+ 1427.8s] [real_gap_vrp] [GAP-VRP] step3: VRP build + validation
[+ 1439.4s] [real_gap_vrp] [GAP-VRP] step3 progress: agents=1/6, routes=5, unassigned=0
[+ 1442.6s] [real_gap_vrp] [GAP-VRP] step3 progress: agents=2/6, routes=15, unassigned=0
[+ 1442.8s] [real_gap_vrp] [GAP-VRP] step3 progress: agents=3/6, routes=18, unassigned=0
[+ 1442.8s] [real_gap_vrp] [GAP-VRP] step3 progress: agents=4/6, routes=19, unassigned=0

,algorithm,feasible,all_checks_ok,assigned_routes,unassigned_tasks,active_agents,transport_work_ton_km,total_km,deadhead_km,deadhead_share_pct,total_hours,runtime_sec
0,real_gap_vrp,True,True,32,0,6,419.865,932.842,556.686,59.676,45.908,1449.481
1,real_milp,True,True,32,0,23,1941.714,4510.761,2257.362,50.044,190.646,107.140
2,real_genetic,True,True,32,0,32,1941.714,4627.014,2373.615,51.299,195.709,342.158

In [10]:
# Schedule map (graph with route scheduling)
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import plotly.express as px

from flowopt.backend.io import load_dataset
from flowopt.solvers import real_gap_vrp_solver, real_milp_solver, real_genetic_solver
from flowopt import gap_vrp_solver as gap_core
from flowopt.dataset import RoutingDataset
import flowopt.core as core

SCHEDULE_ALGO = "real_gap_vrp"  # real_gap_vrp | real_milp | real_genetic
MAP_INTERACTIVE = True
MAP_SHOW_SOLVER_PROGRESS = False

MAP_OUT_DIR = REPO_ROOT / "notebooks" / "local" / "real_data" / "u50_fast_uniform" / factor_tag
MAP_OUT_DIR.mkdir(parents=True, exist_ok=True)
SCHEDULE_MAP_PATH = MAP_OUT_DIR / f"schedule_map_{SCHEDULE_ALGO}_{factor_tag}.png"
SCHEDULE_PLAN_PATH = MAP_OUT_DIR / f"schedule_plan_{SCHEDULE_ALGO}_{factor_tag}.json"

# Re-run selected solver to get full routes/states object for rendering.
dataset_obj, payload_obj = load_dataset(DATASET_PATH)
graph_obj = core.build_nx_graph(dataset_obj)
cache_obj: dict[tuple[str, str], tuple[list[str], float] | None] = {}

if SCHEDULE_ALGO == "real_gap_vrp":
    solver_result = real_gap_vrp_solver.solve_real_gap_vrp(
        dataset=dataset_obj,
        payload=payload_obj,
        graph=graph_obj,
        cache=cache_obj,
        step1_method=GAP_STEP1_METHOD,
        gap_iter=GAP_ITER,
        use_repair=True,
        show_progress=MAP_SHOW_SOLVER_PROGRESS,
        verbose=False,
    )
elif SCHEDULE_ALGO == "real_milp":
    solver_result = real_milp_solver.solve_real_milp(
        dataset=dataset_obj,
        payload=payload_obj,
        graph=graph_obj,
        cache=cache_obj,
        time_limit_sec=RMILP_TIME_LIMIT_SEC,
        unassigned_penalty=RMILP_UNASSIGNED_PENALTY,
        show_progress=MAP_SHOW_SOLVER_PROGRESS,
    )
elif SCHEDULE_ALGO == "real_genetic":
    effective_generations = GA_GENERATIONS
    if GA_GENERATION_SCALE > 0:
        effective_generations = max(GA_MIN_GENERATIONS, int(round(GA_GENERATIONS * GA_GENERATION_SCALE)))
    solver_result = real_genetic_solver.solve_real_genetic(
        dataset=dataset_obj,
        payload=payload_obj,
        graph=graph_obj,
        cache=cache_obj,
        population_size=GA_POPULATION_SIZE,
        generations=effective_generations,
        elite_size=GA_ELITE_SIZE,
        seed=GA_SEED,
        show_progress=MAP_SHOW_SOLVER_PROGRESS,
    )
else:
    raise ValueError(f"Unknown SCHEDULE_ALGO={SCHEDULE_ALGO}")

print(
    {
        "algorithm": SCHEDULE_ALGO,
        "assigned_routes": len(solver_result.routes),
        "unassigned": len(solver_result.unassigned),
        "active_agents": sum(1 for s in solver_result.states.values() if s.task_ids),
        "feasible": solver_result.feasible,
    }
)

if not solver_result.routes:
    raise RuntimeError("No routes in solver_result, schedule map cannot be rendered")

# GAP-LP uses generated task ids (LP_T...), so for rendering switch task table to step1-generated tasks.
dataset_for_render = dataset_obj
route_task_ids = {tid for route in solver_result.routes for tid in route.task_ids}
base_task_ids = {t.task_id for t in dataset_obj.tasks}

if not route_task_ids.issubset(base_task_ids):
    if SCHEDULE_ALGO != "real_gap_vrp":
        missing = sorted(route_task_ids - base_task_ids)[:5]
        raise RuntimeError(f"Route task ids missing in dataset tasks: sample={missing}")

    if GAP_STEP1_METHOD == "lp":
        generated_tasks = gap_core.generate_tasks_lp(
            dataset_obj,
            graph_obj,
            cache_obj,
            show_progress=MAP_SHOW_SOLVER_PROGRESS,
        )
    else:
        generated_tasks = gap_core.generate_tasks_greedy(
            dataset_obj,
            graph_obj,
            cache_obj,
            show_progress=MAP_SHOW_SOLVER_PROGRESS,
        )

    generated_task_ids = {t.task_id for t in generated_tasks}
    if not route_task_ids.issubset(generated_task_ids):
        missing = sorted(route_task_ids - generated_task_ids)[:5]
        raise RuntimeError(f"Route task ids missing in generated step1 tasks: sample={missing}")

    dataset_for_render = RoutingDataset(
        graph=dataset_obj.graph,
        fleet=dataset_obj.fleet,
        tasks=generated_tasks,
        routes=dataset_obj.routes,
        metadata=dataset_obj.metadata,
    )
    print(
        "Render uses generated step1 tasks:",
        {"generated_tasks": len(generated_tasks), "method": GAP_STEP1_METHOD},
    )

core.render_solution_map(
    dataset_for_render,
    graph_obj,
    cache_obj,
    solver_result.routes,
    solver_result.states,
    SCHEDULE_MAP_PATH,
)

# Save route plan for further debug/replay.
plan_payload = core.build_solution_plan(
    solver_result.routes,
    dataset_for_render,
    solver_result.states,
)
SCHEDULE_PLAN_PATH.write_text(json.dumps(plan_payload, ensure_ascii=False, indent=2), encoding="utf-8")

print("Saved map :", SCHEDULE_MAP_PATH)
print("Saved plan:", SCHEDULE_PLAN_PATH)

img = mpimg.imread(SCHEDULE_MAP_PATH)
if MAP_INTERACTIVE:
    fig = px.imshow(img, title=f"Schedule map: {SCHEDULE_ALGO} ({factor_tag})", origin="upper")
    fig.update_xaxes(showticklabels=False)
    fig.update_yaxes(showticklabels=False)
    fig.update_layout(width=1200, height=850, margin=dict(l=10, r=10, t=40, b=10))
    fig.show()
else:
    plt.figure(figsize=(14, 10))
    plt.imshow(img)
    plt.axis("off")
    plt.title(f"Schedule map: {SCHEDULE_ALGO} ({factor_tag})")
    plt.show()

{'algorithm': 'real_gap_vrp', 'assigned_routes': 32, 'unassigned': 0, 'active_agents': 6, 'feasible': True}
Render uses generated step1 tasks: {'generated_tasks': 32, 'method': 'lp'}
Saved map : C:\Users\Пользователь\Optimization-of-flows-3\notebooks\local\real_data\u50_fast_uniform\f10\schedule_map_real_gap_vrp_f10.png
Saved plan: C:\Users\Пользователь\Optimization-of-flows-3\notebooks\local\real_data\u50_fast_uniform\f10\schedule_plan_real_gap_vrp_f10.json

In [ ]:
# Optional detailed columns
detail_cols = [
    "algorithm",
    "checks",
    "solver_error",
    "step1_method",
    "gap_iter",
    "used_agents",
    "time_limit_sec",
    "unassigned_penalty",
    "population_size",
    "generations",
    "generations_requested",
    "generation_scale",
    "elite_size",
]
benchmark_df[[c for c in detail_cols if c in benchmark_df.columns]]

,algorithm,checks,step1_method,gap_iter,used_agents,time_limit_sec,unassigned_penalty,population_size,generations,generations_requested,generation_scale,elite_size
0,real_gap_vrp,"{'hard_constraints_ok': True, 'daily_limits_ok': True, 'reachability_ok': True, 'all_tasks_assigned': True, 'mno_coverage_ok': True, 'all_checks_ok': True}",lp,20.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,real_milp,"{'hard_constraints_ok': True, 'daily_limits_ok': True, 'reachability_ok': True, 'all_tasks_assigned': True, 'mno_coverage_ok': True, 'all_checks_ok': True}",NaN,NaN,NaN,90.0,10000000.0,NaN,NaN,NaN,NaN,NaN
2,real_genetic,"{'hard_constraints_ok': True, 'daily_limits_ok': True, 'reachability_ok': True, 'all_tasks_assigned': True, 'mno_coverage_ok': True, 'all_checks_ok': True}",NaN,NaN,NaN,NaN,NaN,20.0,20.0,20.0,1.0,3.0

In [ ]:
# Optional: agent/task breakdown tables
from flowopt.reporting import solution_breakdown_tables
from IPython.display import Markdown, display

MAX_AGENTS_TO_SHOW = 30
MAX_TASK_IDS_IN_CELL = 12
MAX_TASK_ROWS_TO_SHOW = 300

for _, row in benchmark_df.iterrows():
    algo = row.get("algorithm", "unknown")
    tables = solution_breakdown_tables(
        row,
        max_agents=MAX_AGENTS_TO_SHOW,
        max_task_ids=MAX_TASK_IDS_IN_CELL,
    )

    display(Markdown(f"### {algo}: решение по агентам"))
    display(tables["summary"])

    if tables["agents"].empty:
        print("No active agents in solution")
        continue

    display(tables["agents"])
    display(Markdown(f"**{algo}: задача -> агент (первые {MAX_TASK_ROWS_TO_SHOW} строк)**"))
    display(tables["tasks"].head(MAX_TASK_ROWS_TO_SHOW))

### real_gap_vrp: решение по агентам

,algorithm,active_agents,assigned_tasks,total_mass_tons,total_km,total_hours
0,real_gap_vrp,6,32,0.0,932.843,45.908

,agent_id,vehicle_type,is_compact,tasks_count,routes_count,total_mass_tons,total_km,deadhead_km,deadhead_share_pct,total_hours,task_ids
0,AGENT_00254,VT_AB,False,10,10,0,237.760,140.055,58.906,12.107,"LP_T0002, LP_T0020, LP_T0010, LP_T0005, LP_T0015, LP_T0012, LP_T0013, LP_T0000, LP_T0021, LP_T0030"
1,AGENT_00316,VT_AB,False,7,7,0,177.783,99.710,56.085,8.948,"LP_T0014, LP_T0009, LP_T0011, LP_T0018, LP_T0006, LP_T0007, LP_T0008"
2,AGENT_00124,VT_AB,False,6,6,0,132.783,66.903,50.385,6.853,"LP_T0023, LP_T0019, LP_T0025, LP_T0001, LP_T0004, LP_T0003"
3,AGENT_00252,VT_AB,False,5,5,0,180.895,107.573,59.467,8.637,"LP_T0016, LP_T0026, LP_T0027, LP_T0028, LP_T0029"
4,AGENT_00251,VT_AB,False,3,3,0,80.262,51.837,64.585,4.004,"LP_T0022, LP_T0024, LP_T0017"
5,AGENT_00516,VT_ABD,False,1,1,0,123.360,90.608,73.450,5.360,LP_T0031

**real_gap_vrp: задача -> агент (первые 300 строк)**

       algorithm     agent_id  task_order   task_id
0   real_gap_vrp  AGENT_00254           1  LP_T0002
1   real_gap_vrp  AGENT_00254           2  LP_T0020
2   real_gap_vrp  AGENT_00254           3  LP_T0010
3   real_gap_vrp  AGENT_00254           4  LP_T0005
4   real_gap_vrp  AGENT_00254           5  LP_T0015
5   real_gap_vrp  AGENT_00254           6  LP_T0012
6   real_gap_vrp  AGENT_00254           7  LP_T0013
7   real_gap_vrp  AGENT_00254           8  LP_T0000
8   real_gap_vrp  AGENT_00254           9  LP_T0021
9   real_gap_vrp  AGENT_00254          10  LP_T0030
10  real_gap_vrp  AGENT_00316           1  LP_T0014
11  real_gap_vrp  AGENT_00316           2  LP_T0009
12  real_gap_vrp  AGENT_00316           3  LP_T0011
13  real_gap_vrp  AGENT_00316           4  LP_T0018
14  real_gap_vrp  AGENT_00316           5  LP_T0006
15  real_gap_vrp  AGENT_00316           6  LP_T0007
16  real_gap_vrp  AGENT_00316           7  LP_T0008
17  real_gap_vrp  AGENT_00124           1  LP_T0023
18  real_gap_vrp  AGENT_00124           2  LP_T0019
19  real_gap_vrp  AGENT_00124           3  LP_T0025
20  real_gap_vrp  AGENT_00124           4  LP_T0001
21  real_gap_vrp  AGENT_00124           5  LP_T0004
22  real_gap_vrp  AGENT_00124           6  LP_T0003
23  real_gap_vrp  AGENT_00252           1  LP_T0016
24  real_gap_vrp  AGENT_00252           2  LP_T0026
25  real_gap_vrp  AGENT_00252           3  LP_T0027
26  real_gap_vrp  AGENT_00252           4  LP_T0028
27  real_gap_vrp  AGENT_00252           5  LP_T0029
28  real_gap_vrp  AGENT_00251           1  LP_T0022
29  real_gap_vrp  AGENT_00251           2  LP_T0024
30  real_gap_vrp  AGENT_00251           3  LP_T0017
31  real_gap_vrp  AGENT_00516           1  LP_T0031

### real_milp: решение по агентам

,algorithm,active_agents,assigned_tasks,total_mass_tons,total_km,total_hours
0,real_milp,23,32,37.617,4510.761,190.646

,agent_id,vehicle_type,is_compact,tasks_count,routes_count,total_mass_tons,total_km,deadhead_km,deadhead_share_pct,total_hours,task_ids
0,AGENT_00051,VT_AB,False,3,3,11.686,277.943,134.896,48.534,12.241,"TASK_04481, TASK_18897, TASK_24673"
1,AGENT_00030,VT_A,False,2,2,1.304,196.868,60.152,30.555,8.012,"TASK_04529, TASK_25152"
2,AGENT_00611,VT_A,False,2,2,1.889,267.166,133.790,50.077,10.716,"TASK_02958, TASK_03016"
3,AGENT_00300,VT_A,False,2,2,1.206,270.965,141.291,52.144,10.862,"TASK_07218, TASK_19026"
4,AGENT_00081,VT_AB,False,2,2,1.380,290.541,145.583,50.108,12.546,"TASK_01210, TASK_23276"
5,AGENT_00275,VT_AB,False,2,2,1.933,308.896,154.514,50.021,13.311,"TASK_13159, TASK_10706"
6,AGENT_00254,VT_AB,False,2,2,2.024,313.164,157.546,50.308,13.489,"TASK_12548, TASK_24166"
7,AGENT_00255,VT_AB,False,2,2,1.247,318.950,161.516,50.640,13.730,"TASK_09403, TASK_13014"
8,AGENT_00333,VT_AB,False,1,1,3.452,41.332,25.991,62.882,1.942,TASK_25035
9,AGENT_00342,VT_AB,False,1,1,1.151,128.647,67.503,52.471,5.580,TASK_19520
10,AGENT_00020,VT_A,False,1,1,1.068,131.162,65.787,50.157,5.265,TASK_02580
11,AGENT_00117,VT_AB,False,1,1,0.937,131.366,66.650,50.736,5.694,TASK_02641
12,AGENT_00082,VT_AB,False,1,1,1.068,133.778,67.095,50.154,5.794,TASK_02354
13,AGENT_00083,VT_AB,False,1,1,0.580,151.402,76.058,50.236,6.528,TASK_28664
14,AGENT_00618,VT_AD,False,1,1,0.966,151.785,76.249,50.235,6.058,TASK_17808
15,AGENT_00061,VT_AB,False,1,1,0.836,153.340,79.703,51.978,6.609,TASK_15511
16,AGENT_00277,VT_AD,False,1,1,0.827,158.714,79.391,50.022,6.324,TASK_08880
17,AGENT_00250,VT_AB,False,1,1,0.376,163.622,83.166,50.828,7.038,TASK_08647
18,AGENT_00391,VT_A,True,1,1,0.928,178.143,93.725,52.612,7.072,TASK_08108
19,AGENT_00252,VT_AB,False,1,1,0.844,182.578,93.128,51.007,7.827,TASK_07846
20,AGENT_00443,VT_AB,False,1,1,0.758,184.274,96.790,52.525,7.898,TASK_11997
21,AGENT_00467,VT_AB,False,1,1,0.724,185.450,97.378,52.509,7.947,TASK_18137
22,AGENT_00251,VT_AB,False,1,1,0.433,190.674,99.461,52.163,8.165,TASK_07922

**real_milp: задача -> агент (первые 300 строк)**

    algorithm     agent_id  task_order     task_id
0   real_milp  AGENT_00051           1  TASK_04481
1   real_milp  AGENT_00051           2  TASK_18897
2   real_milp  AGENT_00051           3  TASK_24673
3   real_milp  AGENT_00030           1  TASK_04529
4   real_milp  AGENT_00030           2  TASK_25152
5   real_milp  AGENT_00611           1  TASK_02958
6   real_milp  AGENT_00611           2  TASK_03016
7   real_milp  AGENT_00300           1  TASK_07218
8   real_milp  AGENT_00300           2  TASK_19026
9   real_milp  AGENT_00081           1  TASK_01210
10  real_milp  AGENT_00081           2  TASK_23276
11  real_milp  AGENT_00275           1  TASK_13159
12  real_milp  AGENT_00275           2  TASK_10706
13  real_milp  AGENT_00254           1  TASK_12548
14  real_milp  AGENT_00254           2  TASK_24166
15  real_milp  AGENT_00255           1  TASK_09403
16  real_milp  AGENT_00255           2  TASK_13014
17  real_milp  AGENT_00333           1  TASK_25035
18  real_milp  AGENT_00342           1  TASK_19520
19  real_milp  AGENT_00020           1  TASK_02580
20  real_milp  AGENT_00117           1  TASK_02641
21  real_milp  AGENT_00082           1  TASK_02354
22  real_milp  AGENT_00083           1  TASK_28664
23  real_milp  AGENT_00618           1  TASK_17808
24  real_milp  AGENT_00061           1  TASK_15511
25  real_milp  AGENT_00277           1  TASK_08880
26  real_milp  AGENT_00250           1  TASK_08647
27  real_milp  AGENT_00391           1  TASK_08108
28  real_milp  AGENT_00252           1  TASK_07846
29  real_milp  AGENT_00443           1  TASK_11997
30  real_milp  AGENT_00467           1  TASK_18137
31  real_milp  AGENT_00251           1  TASK_07922

### real_genetic: решение по агентам

,algorithm,active_agents,assigned_tasks,total_mass_tons,total_km,total_hours
0,real_genetic,32,32,37.617,4627.014,195.709

,agent_id,vehicle_type,is_compact,tasks_count,routes_count,total_mass_tons,total_km,deadhead_km,deadhead_share_pct,total_hours,task_ids
0,AGENT_00083,VT_AB,False,1,1,9.779,32.007,21.488,67.136,1.554,TASK_18897
1,AGENT_00344,VT_AB,False,1,1,3.452,41.332,25.991,62.882,1.942,TASK_25035
2,AGENT_00617,VT_AD,False,1,1,1.088,123.787,62.886,50.802,4.981,TASK_04529
3,AGENT_00020,VT_A,False,1,1,1.063,127.622,65.117,51.024,5.129,TASK_04481
4,AGENT_00333,VT_AB,False,1,1,1.151,128.647,67.503,52.471,5.580,TASK_19520
5,AGENT_00061,VT_AB,False,1,1,1.068,131.162,65.787,50.157,5.685,TASK_02580
6,AGENT_00620,VT_AD,False,1,1,0.937,131.366,66.650,50.736,5.273,TASK_02641
7,AGENT_00316,VT_AB,False,1,1,0.815,131.915,71.766,54.403,5.716,TASK_07218
8,AGENT_00124,VT_AB,False,1,1,1.068,133.778,67.095,50.154,5.794,TASK_02354
9,AGENT_00085,VT_AB,False,1,1,0.933,134.221,67.317,50.154,5.813,TASK_02958
10,AGENT_00117,VT_AB,False,1,1,0.956,134.569,68.097,50.603,5.827,TASK_03016
11,AGENT_00611,VT_A,False,1,1,0.844,140.460,70.437,50.147,5.622,TASK_24673
12,AGENT_00081,VT_AB,False,1,1,0.828,141.787,71.206,50.221,6.128,TASK_01210
13,AGENT_00300,VT_A,False,1,1,0.391,144.583,75.058,51.913,5.781,TASK_19026
14,AGENT_00118,VT_AB,False,1,1,0.552,149.370,74.993,50.206,6.444,TASK_23276
15,AGENT_00619,VT_AD,False,1,1,0.580,151.402,76.058,50.236,6.043,TASK_28664
16,AGENT_00082,VT_AB,False,1,1,0.966,151.785,76.249,50.235,6.544,TASK_17808
17,AGENT_00051,VT_AB,False,1,1,0.836,153.340,79.703,51.978,6.609,TASK_15511
18,AGENT_00080,VT_AB,False,1,1,0.216,154.545,78.730,50.943,6.659,TASK_25152
19,AGENT_00618,VT_AD,False,1,1,0.403,155.080,79.832,51.478,6.185,TASK_09403
20,AGENT_00254,VT_AB,False,1,1,1.074,155.574,77.853,50.042,6.702,TASK_13159
21,AGENT_00277,VT_AD,False,1,1,1.012,155.582,78.754,50.619,6.204,TASK_12548
22,AGENT_00249,VT_A,False,1,1,0.859,156.731,80.069,51.087,6.248,TASK_10706
23,AGENT_00252,VT_AB,False,1,1,1.012,158.493,79.702,50.287,6.824,TASK_24166
24,AGENT_00250,VT_AB,False,1,1,0.827,158.714,79.391,50.022,6.833,TASK_08880
25,AGENT_00255,VT_AB,False,1,1,0.376,163.622,83.166,50.828,7.038,TASK_08647
26,AGENT_00251,VT_AB,False,1,1,0.844,164.422,82.235,50.014,7.071,TASK_13014
27,AGENT_00538,VT_ABD,False,1,1,0.928,178.143,93.725,52.612,7.643,TASK_08108
28,AGENT_00275,VT_AB,False,1,1,0.844,182.578,93.128,51.007,7.827,TASK_07846
29,AGENT_00516,VT_ABD,False,1,1,0.758,184.274,96.790,52.525,7.898,TASK_11997

**real_genetic: задача -> агент (первые 300 строк)**

       algorithm     agent_id  task_order     task_id
0   real_genetic  AGENT_00083           1  TASK_18897
1   real_genetic  AGENT_00344           1  TASK_25035
2   real_genetic  AGENT_00617           1  TASK_04529
3   real_genetic  AGENT_00020           1  TASK_04481
4   real_genetic  AGENT_00333           1  TASK_19520
5   real_genetic  AGENT_00061           1  TASK_02580
6   real_genetic  AGENT_00620           1  TASK_02641
7   real_genetic  AGENT_00316           1  TASK_07218
8   real_genetic  AGENT_00124           1  TASK_02354
9   real_genetic  AGENT_00085           1  TASK_02958
10  real_genetic  AGENT_00117           1  TASK_03016
11  real_genetic  AGENT_00611           1  TASK_24673
12  real_genetic  AGENT_00081           1  TASK_01210
13  real_genetic  AGENT_00300           1  TASK_19026
14  real_genetic  AGENT_00118           1  TASK_23276
15  real_genetic  AGENT_00619           1  TASK_28664
16  real_genetic  AGENT_00082           1  TASK_17808
17  real_genetic  AGENT_00051           1  TASK_15511
18  real_genetic  AGENT_00080           1  TASK_25152
19  real_genetic  AGENT_00618           1  TASK_09403
20  real_genetic  AGENT_00254           1  TASK_13159
21  real_genetic  AGENT_00277           1  TASK_12548
22  real_genetic  AGENT_00249           1  TASK_10706
23  real_genetic  AGENT_00252           1  TASK_24166
24  real_genetic  AGENT_00250           1  TASK_08880
25  real_genetic  AGENT_00255           1  TASK_08647
26  real_genetic  AGENT_00251           1  TASK_13014
27  real_genetic  AGENT_00538           1  TASK_08108
28  real_genetic  AGENT_00275           1  TASK_07846
29  real_genetic  AGENT_00516           1  TASK_11997
30  real_genetic  AGENT_00471           1  TASK_18137
31  real_genetic  AGENT_00253           1  TASK_07922